### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by subvertallchris** [cgriego/active_attr#144]
I have a few PRs that I'd like to submit to improve performance, but I noticed that things seem a little quiet. Do you mind sharing your plans for the project and whether you want to keep supporting it?

**Comment by benatkin** [comment]
:+1:

**Comment by aderyabin** [comment]
:+1:

**Comment by cgriego** [comment]
Hi @subvertallchris, I'm not dead yet. I want to hear about the pull requests you'd like to make. I'm impressed with how neo4jrb has integrated ActiveAttr and it's very much inline with how the goals I have for ActiveAttr. Particularly how you define your own base model class from ActiveAttr components and use that. I actually consider using ActiveAttr::Model an anti pattern myself. Maybe we should chat on the neo4jrb gitter sometime?

**Comment by subvertallchris** [comment]
Hey @cgriego! It's really cool to hear from you!

As it happens, just a week or two ago, I duplicated the pieces of ActiveAttr that we've been relying on, added them to our gem, and made some modifications to cut down on duplication. We were only using pieces a few methods and with the state of the project seemingly in flux, I wanted to start working towards a home-grown solution. I hope you understand!

I'm still more than happy to talk with you about it and contribute however I can, though. Pop into Gitter any time, I'm logged in all day, every day during the week and love chatting about this stuff.
