### ISSUE TITLE
documentation for a new Typecaster

### ISSUE THREAD

**Issue by mathieujobin** [cgriego/active_attr#146]
I can't find any documentation on writing a new Typecaster class for a custom class?

what is the minimum implementation ? 

I looked at the IntegerTypecaster and BigDecimalTypecaster

https://github.com/cgriego/active_attr/blob/master/lib/active_attr/typecasting/big_decimal_typecaster.rb

they only implement `call`, which I did as well. I tried to add my typecaster class with in the same module. but it does not work.

is there maybe some sort of registration required?

I am obviously getting the `ActiveAttr::Typecasting::UnknownTypecasterError (Unable to cast to type AndesTime):`

exception

**Comment by mathieujobin** [comment]
I just found the frozen TYPECASTER_MAP , I must need to do something with this boy...

**Comment by mathieujobin** [comment]
I would have prefered if active_attr had a way to register new types... 
or eventually, I'd like to maybe submit this improvement...
but for now, I am overwriting the frozen constant, its bad but it works.

```ruby
tc_map = ActiveAttr::Typecasting::TYPECASTER_MAP.dup
tc_map[AndesTime] = ActiveAttr::Typecasting::AndesTimeTypecaster
ActiveAttr::Typecasting::TYPECASTER_MAP = tc_map
```

by the way, it's impressive how many times `typecaster_for(type)` is being called for a single attribute...
I have a feeling something could be optimized there

anyway. thanks

CC: @jdaudelin @Foutchy

**Comment by cgriego** [comment]
This isn't documented because `TYPECASTER_MAP` isn't part of the public API. Manipulating it will not be supported in future versions. The `:typecaster` option for the `attribute` method is a part of the public API and should be documented.
