### ISSUE TITLE
Undefined methods from shoulda-matchers while testing models, which uses active_attr

### ISSUE THREAD

**Issue by andreydeineko** [cgriego/active_attr#147]
Rails 4.2.4,  rspec-rails 3.3.1, and shoulda-matchers 3.0.0. At this point my tests broke, and tons of errors occurred saying 

```ruby
Failure/Error: it { is_expected.to allow_value('').for(:client_has_active_debit_card) }
       NoMethodError:
         undefined method `allow_value' for #<RSpec::ExampleGroups::ApiParticipant::Validations::OnCreate_2:0x0000000be2ca88>
```
and so on (pointing to methods from shoulda-matchers).

I have asked a [question on StackOverflow](http://stackoverflow.com/questions/33280731/shoulda-matchers-are-not-seen-by-rails-rspec?noredirect=1#comment54397680_33280731), but no one yet seem to know the answer.

I noticed that this only happens in the ```ruby spec/compositions/api``` folder - those are the models where active_attr is used..

**Comment by cgriego** [comment]
active_attr doesn't control these methods defined by shoulda-matchers and doesn't offer any explicit support for shoulda-matchers.
