### ISSUE TITLE
ActiveModel 5 no longer includes ActiveModel::Serializers::Xml

### ISSUE THREAD

**Issue by rmm5t** [cgriego/active_attr#150]
There's now a new (yet to be released) gem to handle the legacy support: https://github.com/rails/activemodel-serializers-xml

* Perhaps XML support should be deprecated from this gem?
* Perhaps the gem should depend on activemodel-serializers-xml?
* Perhaps it should only include `ActiveModel::Serializers::Xml` if the constant exists.

Something akin to the last option might be the best bet.

**Comment by cgriego** [comment]
This is resolved in 0.9.0. From this release forward, if you want XML serialization then you'll have to include `ActiveModel::Serializers::Xml` manually. It is still supported and backed by tests. Thanks for reporting this issue. :+1:

**Comment by rmm5t** [comment]
Thanks, but I don't see a 0.9.0 release on https://rubygems.org/gems/active_attr yet.

**Comment by cgriego** [comment]
Whoops. Try again.

**Comment by rmm5t** [comment]
:+1: :beers:
