### ISSUE TITLE
Issue when using with responders

### ISSUE THREAD

**Issue by d3crypt3d** [cgriego/active_attr#155]
When I try to use a model instance with responders the controller raises an error: **NoMethodError: undefined method `texts_url'**
```
# app/models/text.rb
class Text
  include ActiveAttr::Model

  attribute :plain
  attribute :encrypted
  attribute :frequency
end

# app/controllers/crypt_controller.rb
class CryptController < ApplicationController
   respond_to :json
 
  def encrypt
    respond_with Text.new(plain: @text, encrypted: output, frequency: frequency_analisys(output)), status: :ok
  end
  # ...
end
```
ERROR NoMethodError: undefined method `texts_url' for #<CryptController:0x000000074745f8>
/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/polymorphic_routes.rb:220:in `polymorphic_method'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/polymorphic_routes.rb:114:in `polymorphic_url'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/url_for.rb:164:in `url_for'

**Comment by cgriego** [comment]
I'm not sure why anything would be trying to create a URL from just this sample code. Can you provide the full backtrace?

**Comment by d3crypt3d** [comment]
/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/polymorphic_routes.rb:220:in `polymorphic_method'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/polymorphic_routes.rb:114:in `polymorphic_url'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/url_for.rb:164:in `url_for'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:95:in `_process_options'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/streaming.rb:200:in `_process_options'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/renderers.rb:43:in `block in _render_to_body_with_renderer'
	/home/workstat/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/set.rb:263:in `each_key'
	/home/workstat/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/set.rb:263:in `each'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/abstract_controller/rendering.rb:25:in `render'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:16:in `render'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
	/home/workstat/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/responders-2.1.1/lib/action_controller/responder.rb:258:in `display'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/responders-2.1.1/lib/action_controller/responder.rb:214:in `api_behavior'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/responders-2.1.1/lib/action_controller/responder.rb:191:in `rescue in to_format'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/responders-2.1.1/lib/action_controller/responder.rb:185:in `to_format'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/responders-2.1.1/lib/action_controller/responder.rb:163:in `respond'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/responders-2.1.1/lib/action_controller/responder.rb:156:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/responders-2.1.1/lib/action_controller/respond_with.rb:205:in `respond_with'
	/home/workstat/development/lightit_test_task/caesar_cipher/app/controllers/crypt_controller.rb:20:in `encrypt'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:198:in `process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:117:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:505:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `block in instrument'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:164:in `instrument'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activerecord-4.2.5.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/abstract_controller/base.rb:137:in `process'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionview-4.2.5.1/lib/action_view/rendering.rb:30:in `process'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal.rb:196:in `dispatch'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_controller/metal.rb:237:in `block in action'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:30:in `each'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/journey/router.rb:30:in `serve'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/routing/route_set.rb:815:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activerecord-4.2.5.1/lib/active_record/query_cache.rb:36:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/railties-4.2.5.1/lib/rails/rack/logger.rb:38:in `call_app'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/railties-4.2.5.1/lib/rails/rack/logger.rb:20:in `block in call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:26:in `tagged'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/tagged_logging.rb:68:in `tagged'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/railties-4.2.5.1/lib/rails/rack/logger.rb:20:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/static.rb:116:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/railties-4.2.5.1/lib/rails/engine.rb:518:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/railties-4.2.5.1/lib/rails/application.rb:165:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/home/workstat/.rvm/gems/ruby-2.1.4@rails4/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/home/workstat/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
	/home/workstat/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
	/home/workstat/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'

**Comment by cgriego** [comment]
The reason this is happening is because the request is a POST, which the responders gem assumes is used for creating a resource and, like would be created when generating a Rails scaffold controller in a create action, the responders gem is trying to communicate the Location header for the resource and that's where it's trying to generate a URL for the given model. However there isn't a resources route defined for your Text model and that's why it fails. You could override the `:location` option if you have something suitable, but if not then the responders gem is probably too generalized for your use case.

```ruby
      elsif post?
        display resource, :status => :created, :location => api_location
```
