### ISSUE TITLE
Add support for Rails 5.2

### ISSUE THREAD

**Issue by rmm5t** [cgriego/active_attr#163]
Likely just requires relaxing the gemspec. 

Rails 5.2 is just around the corner, but this gem currently limits support to `">= 3.0.2", "< 5.2"`.

I have another project that depends on active_attr as a dev dependency, and I was able to get things tested against 5.2.0.rc1, but once 5.2.0 is officially released, the dependencies will no longer resolve.

**Comment by cgriego** [comment]
Fixed with 0.10.3
