### ISSUE TITLE
Need help with release management and issue/PR triage?

### ISSUE THREAD

**Issue by mathieujobin** [cgriego/active_attr#197]
I have 35 gems under my responsibility.

https://rubygems.org/profiles/mathieu

If you need some help, your gem is safe with me.

I will release the support for rails 7.1 shortly after.

cheers,

**Comment by cgriego** [comment]
Hi Mathieu, not looking to turn over access currently, but appreciate the offer.
I've opened up the Discussions tab on this repository which may help some.
