### ISSUE TITLE
Support Rails 7.2

### ISSUE THREAD

**Issue by elliotlarson** [cgriego/active_attr#201]
It looks like `active_attr` does not support Rails 7.2 at this point:

> Could not find compatible versions
> Because active_attr >= 0.16.0 depends on activesupport >= 3.0.2, < 7.2
  and rails >= 7.2.0 depends on activesupport = 7.2.0,
  active_attr >= 0.16.0 is incompatible with rails >= 7.2.0.
> So, because Gemfile depends on rails ~> 7.2
  and Gemfile depends on active_attr ~> 0.16,
  version solving has failed.

**Comment by brandondrew** [comment]
Is this simply a case of it not yet being tested?

**Comment by elliotlarson** [comment]
Yeah, my guess is that it probably will work out of the box but that the limitation was put in place to guard against potential breaking changes in an ActiveSupport version upgrade.

**Comment by aramprice** [comment]
See also https://github.com/cgriego/active_attr/pull/202

**Comment by elliotlarson** [comment]
Sweet! Thank you, @cgriego.
